return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "docker-compose-language-service",
      "docker-language-server",
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "clangd",
      "clang-format",
      "cpplint",
      "hadolint",
      "yamllint",
      "html-lsp",
      "css-lsp",
      "emmet-language-server",
      "jdtls",
      "gopls",
      "delve",
      "eslint-lsp",
    },
  },
}
